@baseUrl = http://localhost:3333
# @authToken = {{authenticate.response.body.accessToken}}

# @name get-company-technical
GET http://localhost:3333/tecnicos/TECNICOAPP/1/empresas

###

# @name get-users
GET http://localhost:3333/usuarios/1/names

###

# @name get-users
GET http://localhost:3333/teste

###

# @name get-all-medidores-by-contrato
GET http://localhost:3333/tecnicos/1/12/22/todos-medidores-contrato

###

# @name get-amount-chamados
GET http://localhost:3333/tecnicos/TECNICOAPP/1/quantidade-chamados

###

# @name get-amount-chamados
GET http://localhost:3333/tecnicos/1/4/lista-tipo-medidor-contrato