@baseUrl = http://localhost:3308
# @authToken = {{authenticate.response.body.accessToken}}


### CHAMADOS ###

# @name get-linked-parts
GET {{baseUrl}}/parts/1/1566

###

# @name get-clients
GET {{baseUrl}}/clientes/1

###

# @name get-status
GET {{baseUrl}}/status/1/M

###

# @name get-resumo-chamados
GET {{baseUrl}}/tecnicos/TECNICOAPP/1/resumo-chamados

###

# @name get-all-medidores-by-contrato
GET {{baseUrl}}/tecnicos/1/1/11/23/todos-medidores-contrato

###

# @name get-amount-chamados
GET {{baseUrl}}/tecnicos/TECNICOAPP/1/quantidade-chamados

###

# @name get-list-type-counters
GET {{baseUrl}}/tecnicos/1/4/lista-tipo-medidor-contrato

###

# @name get-detail
GET {{baseUrl}}/chamados/1054763/detail

###

# @name get-all-service-order-technical
POST {{baseUrl}}/tecnico/todos-chamados-tecnico
Content-Type: application/json

{
  "idTecnico": "TECNICO2",
  "idBase": 1,
  "status": "M"
}

###

# @name get-status
GET {{baseUrl}}/status/1/M

###

# @name create-attendance 
POST {{baseUrl}}/atendimentos/add
Content-Type: application/json

{
  "SEQOS": 1430,
  "CDSTATUS": "M1",
  "STATUS": "M",
  "NMATENDENTE": "TESTE",
  "OBSERVACAO": "Início do atendimento",
  "chamado_id": 3261029,
  "empresa_id": 46,
  "ID_BASE": 1,   
  "ATIVO_APP": 1,
  "KMINICIAL": 0,
  "PLACAVEICULO": "ABC-1234",
  "ANDAMENTO_CHAMADO_APP": 1,
  "ORIGEM_CADASTRO": "API TESTE",
  "granted_geolocation": 1,
  "DESLOCAMENTO_APP": 10
}

###

# @name update-attendace
PUT {{baseUrl}}/atendimentos/update
Content-Type: application/json

{
  "id": 13320247,
  "ID_BASE": 1, 
  "progress": 2,
  "params": {
    "HRVIAGEMFIN": "16:08",
    "DTVIAGEMFIN": "2025-01-14T19:43:49.984Z"
  }
}

###

# @name get-all-meters
GET {{baseUrl}}/equipment-meters/1/304

###

# @name update-attendace-meters
POST {{baseUrl}}/atendimentos-medidores/add
Content-Type: application/json

{
    "id": 13320253,
    "ID_BASE": 1,
    "empresa_id": 46, 
    "cdequipamento": 304,
    "informante": "TESTE API",
    "meters_list": [
      {
        "CDMEDIDOR": "SCANNER",
        "MEDIDOR": 1
      },
      {
        "CDMEDIDOR": "CORA4",
        "MEDIDOR": 1
      }
    ]
}

###

# @name get-history
GET {{baseUrl}}/history/1/orders/1430/304

###

# @name get-history-attendance
GET {{baseUrl}}/historico/1/3231230

###

# @name send-sms
POST {{baseUrl}}/send-sms
Content-Type: application/json

{
  "phone": "+5548984467979"
}